### ISSUE TITLE
Dependency wrong

### ISSUE THREAD

**Issue by dirk-thomas** [yujinrobot/yujin_ocs#63]
As being notified for a long time by the build farm: http://jenkins.ros.org/view/IbinT64/job/ros-indigo-yocs-ar-marker-tracking_binarydeb_trusty_amd64/

Using `yaml_cpp`: https://github.com/yujinrobot/yujin_ocs/blob/21e1ccaadef496eddf9c11b518513e944570e278/yocs_ar_marker_tracking/CMakeLists.txt#L22

**Comment by stonier** [comment]
@jihoonl looks like problem crept in with 3ca8cf1d7c609b7b5b7fd08b31ee0538e8cc9966.  Please take a look at this first thing Monday.

Thanks @dirk-thomas.

**Comment by stonier** [comment]
If the pkg-config files are indeed different on different platforms (`yaml_cpp`, `yaml-cpp`) then you have to drop the `REQUIRED` tags and implement your own kind of required check depending on the results.

**Comment by jihoonl** [comment]
CMakeLists updated. 

Ref : https://github.com/ros-planning/navigation/pull/140/files

**Comment by jihoonl** [comment]
Should be fixed. Will release it soon.

**Comment by jihoonl** [comment]
yocs_ waypoint provider and yocs_ar_marker_tracking are failing

http://jenkins.ros.org/job/ros-indigo-yocs-ar-marker-tracking_binarydeb_trusty_i386/121/console
http://jenkins.ros.org/job/ros-indigo-yocs-waypoint-provider_binarydeb_saucy_i386/1/console

**Comment by jihoonl** [comment]
yujin_ocs has passed pre-release test but fails in release..

Prerelease : http://jenkins.ros.org/job/prerelease-indigo-yujin_ocs/2/
release of yocs_waypoint_provider(failed) : http://jenkins.ros.org/job/ros-indigo-yocs-waypoint-provider_binarydeb_trusty_i386/3/console

**Comment by dirk-thomas** [comment]
The release build fails because the specific package is still missing the dependency.

The prerelease passes since it builds all packages of the repo in topological order. And it is likely that one of the packages before `yocs_waypoint_provider` is installing the dependency making it available for later packages.
